spring:
  application:
    name: number-service-eureka-client
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8080/eureka-server/v2/}
  instance:
    preferIpAddress: true